services:
  db:
    image: postgres:16
    container_name: inip_db
    environment:
      POSTGRES_DB: inip
      POSTGRES_USER: inip
      POSTGRES_PASSWORD: inip_password
    ports:
      - "5432:5432"
    volumes:
      - inip_pgdata:/var/lib/postgresql/data

volumes:
  inip_pgdata:
